[soc-classification-library]

[data_source]

soc_index = "src/occupational_classification/data/example_soc_lookup_data.csv"

soc_structure = "src/occupational_classification/data/example_soc_lookup_data.csv"
