[soc-classification-library]

[data_source]

soc_index = "../data/soc2020volume2thecodingindexexcel16042025.xlsx"

soc_structure = "../data/soc2020volume1structureanddescriptionofunitgroupsexcel16042025.xlsx"

[other]
# soc_index = "src/occupational_classification/data/soc2020volume2thecodingindexexcel16042025.xlsx"
# soc_structure = "src/occupational_classification/data/soc2020volume1structureanddescriptionofunitgroupsexcel16042025.xlsx"
