[soc_data]

[lookups]
soc_structure = "src/occupational_classification/data/soc2020volume1structureanddescriptionofunitgroupsexcel16102024.xlsx"

soc_index = "src/occupational_classification/data/soc2020volume2thecodingindexexcel16102024.xlsx"

soc_condensed = "soc_4d_condensed.txt"
